/*
 * This file was automatically generated by EvoSuite
 * Mon May 13 14:19:28 GMT 2019
 */

package com.yoha.server.config;

import org.junit.Test;
import static org.junit.Assert.*;
import com.yoha.server.config.FileUploadConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.web.multipart.MultipartResolver;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileUploadConfig_ESTest extends FileUploadConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileUploadConfig fileUploadConfig0 = new FileUploadConfig();
      MultipartResolver multipartResolver0 = fileUploadConfig0.custom();
      assertNotNull(multipartResolver0);
  }
}
