/*
 * This file was automatically generated by EvoSuite
 * Mon May 13 14:17:56 GMT 2019
 */

package com.yoha.server.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.yoha.server.model.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      User user0 = new User();
      user0.setPassword("UA.a PJ#.&wOpHw");
      String string0 = user0.getPassword();
      assertEquals("UA.a PJ#.&wOpHw", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      User user0 = new User();
      user0.setName("I}V\"B-8Qx5R]-|mc%");
      String string0 = user0.getName();
      assertEquals("I}V\"B-8Qx5R]-|mc%", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      User user0 = new User();
      Integer integer0 = new Integer(0);
      user0.setId(integer0);
      Integer integer1 = user0.getId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      User user0 = new User();
      Integer integer0 = new Integer((-3382));
      user0.setId(integer0);
      Integer integer1 = user0.getId();
      assertEquals((-3382), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      User user0 = new User();
      user0.setPassword("");
      String string0 = user0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      User user0 = new User();
      user0.setName("");
      String string0 = user0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      User user0 = new User();
      Integer integer0 = new Integer(295);
      user0.setId(integer0);
      Integer integer1 = user0.getId();
      assertEquals(295, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      User user0 = new User();
      Integer integer0 = user0.getId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getPassword();
      assertNull(string0);
  }
}
