/*
 * This file was automatically generated by EvoSuite
 * Mon May 13 14:14:18 GMT 2019
 */

package com.yoha.server.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.yoha.server.utils.JwtUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JwtUtil_ESTest extends JwtUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = JwtUtil.validateToken("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        JwtUtil.validateToken((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.auth0.jwt.TokenUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        JwtUtil.generateToken((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The Custom Claim's value class must be an instance of Integer, Double, Boolean, Date or String.
         //
         verifyException("com.auth0.jwt.JWTCreator$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JwtUtil jwtUtil0 = new JwtUtil();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = JwtUtil.generateToken("4.4R>");
      assertEquals("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBUFAiLCJpc3MiOiJMQ0gtWU9IQS1TRVJWRVIiLCJleHAiOjEzOTI0MTY0ODEsImlhdCI6MTM5MjQwOTI4MSwidXNlcm5hbWUiOiI0LjRSPiJ9.LXC9RsJJug8wpcos7r-JG83577kpa4c77uKVLnEviEw", string0);
  }
}
